#!/bin/bash -l
#**********************************************************************
#
#   File: runjob
#
#   A file to run a SLURM job to use the GPU devices
#
#   Submit this job on the QUB Kelvin system with the command
#
#     sbatch runjob
#
#**********************************************************************
#
#SBATCH --job-name=FDTD
#SBATCH -p gpu
#SBATCH --time=16:00:00
#SBATCH --output=/users/40173800/sharedscratch/omp/opencl-fdtd-out-GPU-%j.log
#SBATCH --gres gpu:2

module add nvidia-cuda

module add compilers/gcc/7.2.0

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

time /users/40173800/2DFDTD/bin/getdevinfo.x

for DIM in 500 750 1000 1250 1500 1750 2000 2250 2500 2750 3000 3250 3500 3750 4000 4250 4500 4750 5000 5250 5500 5750 6000
do
        echo "  "
        echo "----------------------------------------------------------"
        echo "  "
        echo "   Running case for DIM = ${DIM} "
        echo "  "

        time /users/40173800/2DFDTD/bin/yee2d.x x=${DIM} y=${DIM} OCL 2>&1
done

#**********************************************************************
#
#   End of file
#
#**********************************************************************


